### ISSUE TITLE
Yakuza 6, in TaskManager only

### ISSUE THREAD

**Issue by Klemci** [ThirteenAG/Ultimate-ASI-Loader#71] opened 2023-09-20 23:55 UTC
i use the Ryu modmanager, so i updated ASILoader in hope, x64, but it didn't help, when i remove the dinput8.dll, game window (fullscreen btw) popups normally, when dll is present, game is only in TakManager (3 PCs tested, B650E/4070 - 9700F/3060 - DeskMini APU 4650G).

I renamed the dll, some filenames are triggering, when it's the case, game doesn't draws window :p

**Comment by ThirteenAG** [comment] 2023-10-26 17:00
Should be fixed in v6.2. If not, let me know.

**Comment by Klemci** [comment] 2023-10-26 19:16
Apparently no, i seen again the EXE in TaskManager only !!

Thanks for investigation done.

**Comment by ThirteenAG** [comment] 2023-10-27 07:05
Sorry, but I can't reproduce with latest version, game launches fine with dinput8.dll, d3d11.dll, winmm.dll, and test asi works.

**Closed by ThirteenAG** 2023-10-27 07:05 UTC
