### ISSUE TITLE
Overload and File Types

### ISSUE THREAD

**Issue by TemporaryPSP** [ThirteenAG/Ultimate-ASI-Loader#86] opened 2024-01-29 09:29 UTC
Recently decided to check up on Ultimate ASI Loader to find the new Overload feature, then tested it on different titles. Ran into an issue with Dead Rising 2 (and Off the Record) textures (UI in this case). With packed files it works great but I'm using HD Frontend that remedies blurry HUD elements but loading it with Overload doesn't quite work.

![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/283ab2d1-4a04-4e2c-91ea-6061452be84b)
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/b7385498-20b9-44fa-ae77-50a0e09f8465)
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/fad51171-99d2-4d9a-bdc3-dc522a623ecc)
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/224dbe72-e70e-4ced-b3c6-d4689bb2bb5f)

**Comment by ThirteenAG** [comment] 2024-01-29 09:33
What doesn't work exactly? On screens I see some kind of corruption, but asi loader wouldn't cause that, since it only redirects paths. I can't tell without more info.

**Comment by ThirteenAG** [comment] 2024-01-29 09:59
Also try using https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/demo-plugins/OverloadFromFolderDLL-Win32.zip in addition to asi loader.

**Comment by TemporaryPSP** [comment] 2024-01-29 19:03
OverloadFromFolderDLL.asi doesn't seem to help unfortunately. Here are the contents of the Overload folder:

![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/75bf9149-0c00-4580-9c21-e20fad235392)
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/db8e2b72-6856-45cb-a7d1-95d4afa214ed)

**Comment by TemporaryPSP** [comment] 2024-01-29 19:08
Tested Overload with loose models/textures (clothes) since the game kind of supports sideloading them without having to repack npcs.big (where they are stored). With Overload, it can't load from the folder.

**Comment by ThirteenAG** [comment] 2024-01-30 02:41
Check with [procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon), filter path to include any of these filenames, and post the log here.

**Comment by TemporaryPSP** [comment] 2024-01-30 17:35
So it has to replace something, yeah? Here's the log in XML.
[Logfile.zip](https://github.com/ThirteenAG/Ultimate-ASI-Loader/files/14102103/Logfile.zip)

**Comment by TemporaryPSP** [comment] 2024-01-30 17:49
So Overload has to replace something? Here's the log:
[Logs.zip](https://github.com/ThirteenAG/Ultimate-ASI-Loader/files/14102231/Logs.zip)

**Comment by ThirteenAG** [comment] 2024-01-30 18:09
> So Overload has to replace something? 

Ideally it should have the matching file without update in path. In some cases might work without that requirement.

The logs seem fine to me, can't explain texture breakage though.

**Comment by TemporaryPSP** [comment] 2024-01-30 19:37
Most if not all HUD elements that are replaced except for the tutorial images (with the corruption) are just blank/black.

![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/5cb90611-906a-437b-9f60-61ef013747dd)
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/c5b1746b-6ed9-4853-a8cd-320337d302a1)

**Comment by ThirteenAG** [comment] 2024-01-31 04:28
Upload something that can be easily reproduced, the files in update folder and a way to reproduce the bug. Maybe I can check some time in the future.

**Comment by TemporaryPSP** [comment] 2024-01-31 07:49
Replace something in data\frontend (update\data\frontend). This is the [HD Frontend](https://www.mediafire.com/file/vwmkgpw2rf989hm/HD_Frontend_v1.0_for_Dead_Rising_2_-_UndeadFrankie.rar/file) I'm using. There's also this [HD VFX](https://www.mediafire.com/file/0ydeo9f0jf3faio/HD_Effects_v.1.0_for_Dead_Rising_2_-_UndeadFrankie.rar/file) mod that crashes the game upon startup if replaced using Overload.

**Comment by ThirteenAG** [comment] 2024-01-31 09:25
> There's also this [HD VFX](https://www.mediafire.com/file/0ydeo9f0jf3faio/HD_Effects_v.1.0_for_Dead_Rising_2_-_UndeadFrankie.rar/file) mod that crashes the game upon startup if replaced using Overload.

I checked that one, it actually explained everything. 
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/4904157/991875d8-661b-4503-9ca2-b0cecbf55633)
The function that reads file, only reads an amount of bytes equal to original filesize. I don't know why yet.

**Comment by ThirteenAG** [comment] 2024-02-01 11:38
[d3d9.zip](https://github.com/ThirteenAG/Ultimate-ASI-Loader/files/14124660/d3d9.zip)

Can you try this build? I can't really make a fix for this, but I added a workaround, toggleable in the ini file.

**Comment by TemporaryPSP** [comment] 2024-02-01 12:40
That did it! The game doesn't crash on startup and the UI loads correctly.

![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/186e4ad9-a47a-46eb-b096-5f8e2d11ecc1)
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/20f2e11c-0bf3-420f-9761-c3096e6c4926)

**Comment by TemporaryPSP** [comment] 2024-02-01 13:21
> The function that reads file, only reads an amount of bytes equal to original filesize.
Makes sense. After reading this I noticed that some HUD elements (that the game managed to load) do look better. So, I tested loading other textures with v6.9.0, a low quality blue jeans texture in the game's directory (loose) and a higher quality black jeans texture in Overload. Here's the result:

![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/ea699784-a41f-4bed-8cba-d404dbaf4290)

Then I replaced the model and texture of the jeans with 0 KB files and had Overload load the original files to see if the game could actually load them. This time, the jeans seemed to load just fine.

**Comment by ThirteenAG** [comment] 2024-02-01 13:27
Okay, thanks for letting me know. I've added a check for this game's exe name, so you don't have to use ini file with the released version of asi loader.

**Comment by TemporaryPSP** [comment] 2024-02-01 13:58
> added a check for this game's exe name

Likewise, thanks for the quick patch. Don't forget about Dead Rising 2: Off the Record (deadrising2otr.exe) and maybe Dead Rising 3 and 4 since they all run on the same engine.

**Comment by ThirteenAG** [comment] 2024-02-01 16:54
If you can test them with an ini option, and provide exe names, I can add.

**Comment by TemporaryPSP** [comment] 2024-02-01 19:20
Tested the Off the Record version of [HD VFX](https://www.mediafire.com/file/2sbwo5yccrx0m83/HD_Effects_v.1.0_for_Dead_Rising_2_-_Off_The_Record_-_UndeadFrankie.rar/file) mod with and without PatchFindFile.

The game crashes without PatchFindFile on startup. With PatchFindFile enabled via .ini, everything works fine. Relaunch the game without the .ini file afterwards and the game still works but effects break (black squares or invisible).

https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/77cf018f-1ba7-4453-a172-04688149e4c7

**Comment by ThirteenAG** [comment] 2024-02-02 13:16
Okay, added those.

**Comment by TemporaryPSP** [comment] 2024-03-23 23:25
Apologies for the bump/comment. Just want to report that the PatchFindFile workaround does have some side effects. Some materials/shaders (?) have the font texture overlaid on top of them.

![Font](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/a46c3955-edc4-4ae7-bdfb-48507c372e36)
![Font2](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/c724f148-560e-4a61-9b87-ff6fa1ea4f91)
![Font3](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/c25538d1-9fae-4912-9e66-fb6999e803ff)

**Comment by ThirteenAG** [comment] 2024-03-25 07:53
And how to reproduce this?

**Comment by ThirteenAG** [comment] 2024-03-25 07:59
Any idea what file this one uses?

![Font](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/a46c3955-edc4-4ae7-bdfb-48507c372e36)

**Comment by TemporaryPSP** [comment] 2024-03-25 21:59
It's **PottedPlant_5**, its assets can be found in **data\streamedassets.big/PottedPlant_5.big**. But the game's path defines it as **data/models/weapons/pottedplant5**.

**Comment by ThirteenAG** [comment] 2024-03-26 02:43
And which file is the font texture? Does deleting it from update "fixes" this?

**Comment by TemporaryPSP** [comment] 2024-03-26 03:11
Probably should've mentioned this in the initial comment. But none of the files inside the update folder touches any of these objects. Enabling PatchFindFile AUTOMATICALLY causes this issue to happen even if update is empty/doesn't exist.

**Comment by ThirteenAG** [comment] 2024-03-26 03:13
Oh, right. Tbh not sure if I can do anything about it.

**Comment by TemporaryPSP** [comment] 2024-03-26 03:37
All good. It's a weird issue anyway, hopefully this doesn't occur in many titles.

**Comment by TemporaryPSP** [comment] 2024-04-02 12:53
But let's say we want to know more about this. How does one debug this? Will Procmon logs of the file loading make any sense?

**Comment by TemporaryPSP** [comment] 2024-04-02 13:18
So, something like this wouldn't help at all?


https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/b7feaec8-d46b-4ebf-bd0b-869838139b59

**Comment by ThirteenAG** [comment] 2024-04-02 13:20
Help to do what?

**Comment by TemporaryPSP** [comment] 2024-04-02 13:21
Help you make sense of this.  It's just weird that the PatchFindFile switch automatically breaks these even though nothing is being replaced.

**Comment by ThirteenAG** [comment] 2024-04-02 13:24
But it already makes sense, as I said in previous post. PatchFindFile affects all files.

**Comment by TemporaryPSP** [comment] 2024-04-02 13:43
I _kind of_ get it now. The reason it doesn't happen with PatchFindFile turned off is because only the files in the update folder get redirected instead of everything? So, technically the best solution is to go back to the root issue (which is the size restriction) and fix that instead of this.

![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/a5c1ae53-de19-431b-af06-7688d4421032)

**Comment by TemporaryPSP** [comment] 2024-04-10 18:27
Briefly tested the new .dll, this seems to get the job done! Problems such as the font texture overlay and others such as missing VFX on specific particles are fixed, and not to mention the previous mods (haven't tested HD VFX) work well.

**Comment by ThirteenAG** [comment] 2024-04-11 03:16
Thanks for letting me know, I'll release an updated version now, but an extra ini option will be removed later, since it's not needed anymore.

**Closed by ThirteenAG** 2024-04-11 03:16 UTC

**Comment by ThirteenAG** [comment] 2024-04-11 03:21
[dinput8.zip](https://github.com/ThirteenAG/Ultimate-ASI-Loader/files/14940779/dinput8.zip)

Uploading a preview version here, no ini file is needed.

**Comment by TemporaryPSP** [comment] 2024-04-11 03:54
What's the difference between the preview .dll and the one pushed in releases?

**Comment by ThirteenAG** [comment] 2024-04-11 03:56
Something I try to test, related to different hooking method.

**Comment by ThirteenAG** [comment] 2024-04-26 02:09
What game are you trying this on?

**Comment by TemporaryPSP** [comment] 2024-04-26 09:39
Watch_Dogs.

**Comment by ThirteenAG** [comment] 2024-04-26 11:46
That has nothing to do with path, the files are loaded with Disrupt_b64.dll, so it needs OverloadFromFolderDLL plugin, but since Disrupt_b64.dll doesn't have direct imports in IAT, it won't be affected by it. You can, again, try my test version with nonIAT hook, but it's currently unstable in some games, so I can't quite release it.
[dinput8_x64.zip](https://github.com/ThirteenAG/Ultimate-ASI-Loader/files/15130112/dinput8_x64.zip)

Path for 
`Watch Dogs\data_win64\patch.dat`
would be
`Watch Dogs\bin\update\data_win64\patch.dat`

First open with regular asi loader, second with the archive from this post:
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/4904157/f6cb7952-465d-490c-a435-0d79c9445570)

**Comment by TemporaryPSP** [comment] 2024-04-26 12:16
So that's why even with OverloadFromDLL it still doesn't work. This experimental DLL seems to do the job just fine.

**Comment by ThirteenAG** [comment] 2024-04-26 12:19
Yeah, some games use functions asi loader hooks in a different manner, so they aren't hooked. It's not that much of a problem for asi loading, but for overloading files it is.

**Comment by TemporaryPSP** [comment] 2024-04-26 14:37
As expected, it crashes in online (when the scores are calculated at the end of a session, not when playing). But at least the Overload works, it's just not feasible to create a special .dll for each game.

**Comment by TemporaryPSP** [comment] 2024-04-26 20:06
Here's the [CrashDump](https://drive.google.com/file/d/16IFfTkAbGuAzMpLbSfWTvj6M8RUVyAsd/view?usp=sharing), hope this can help further the development.

https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/78895214/8b1875dd-2ca3-4f14-a851-889b86ce8b77

**Comment by ThirteenAG** [comment] 2024-04-27 02:35
Doesn't look like it's directly caused by my code, so nothing I can do.

**Comment by TemporaryPSP** [comment] 2024-05-15 10:32
Sorry for bumping a closed thread again. This time Manhunt 2 can't read .fsb audio format in update folder. It's FMOD Ex so tried the OverloadFromFolder and PatchFindFile to no avail. Also is there an easy to access collection of test/experimental iterations for both 32-bit/64-bit (for example, the nonIAT dinput8 plugin you linked for Disrupt_b64 is for 64-bit) just so if people run into things with Overload this will help with troubleshooting.

**Comment by ThirteenAG** [comment] 2024-05-16 04:30
fmodex.dll is under UPX, so iat hooking won't work. I might release a new version with global hook for overload, keeping the previous code intact for compatibility, but I don't have time to make it right now.

**Comment by ThirteenAG** [comment] 2024-05-22 09:46
Check again with v7.3.0.

**Comment by TemporaryPSP** [comment] 2024-05-22 20:02
Well, as I've stated in the update section. .fsb loading does work even with v7.2.0. I relaunched the game several times until it just worked (previously everything in the update folder except .fsb were loaded) and had no problems since. But I'll give v7.3.0 a shot.

**Comment by TemporaryPSP** [comment] 2024-06-24 10:04
Something wrong with the new releases? Does not work on DX8 titles for some reason.

**Comment by ThirteenAG** [comment] 2024-06-24 12:44
Works in gta vc e.g., I don't think anything's wrong.

**Comment by TemporaryPSP** [comment] 2024-09-12 16:35
Long overdue but dinput8.dll suddenly doesn't work for titles such as Manhunt and Max Payne 1 & 2. Had to rename it to d3d8.dll. Sorry for the false negative.

**Comment by TemporaryPSP** [comment] 2025-01-07 04:23
Noticed that Overload just doesn't work in Manhunt. It can't be because it's DX8, right? Some people can make it work by jumping through hoops with wrappers and stuff but I can't get it to work even if the game runs in DX9. Any ideas?

**Comment by ThirteenAG** [comment] 2025-01-07 05:11
Works fine for me.

**Comment by TemporaryPSP** [comment] 2025-01-07 05:32
How's your setup? One person was able to get it working by getting your d3d8 wrapper and renaming UAL to d3d9. Very odd. I tried PatchFindFile, DX8, DX9 and with Procmon I couldn't find any activity involving the update folder.

**Comment by ThirteenAG** [comment] 2025-01-07 05:34
I don't have any setup, just tried widescrren fix's menu files.

**Comment by ThirteenAG** [comment] 2025-01-07 06:59
dinput8 works because widescreen fix uses it like that. d3d8 also works for me. Overload is not related to dll name, should work in any case.

**Comment by TemporaryPSP** [comment] 2025-01-07 07:03
That's why this is so odd. I did a clean reinstall and only used the ASI Loader provided in the widescreen fix itself which comes in dinput8.dll and it doesn't work. Usually I update all ASI Loader to the latest version. I noticed for Max Payne 1 & 2 widescreen fix, UAL is d3d8 for those games. Even after reinstalling I still have to rename the loader to ddraw and even then, the global stuff and Overload doesn't work.

**Comment by ThirteenAG** [comment] 2025-01-07 07:07
ASI Loader in widescreen fix is likely very outdated. And ddraw.dll is not suitable for overloaded in manhunt(don't know why).

**Comment by TemporaryPSP** [comment] 2025-01-07 07:13
Alright. At least now we know that ddraw.dll can't do Overload, I thought it's just a problem on my end. I have no issues with UAL/Overload up until this point so I'll try renaming UAL till the Overload works.

**Comment by ThirteenAG** [comment] 2025-01-07 07:18
Ddraw is unloaded shortly after startup, and all hooks with it.

**Comment by TemporaryPSP** [comment] 2025-01-07 07:20
I found the culprit as to why naming the loader d3d8 or dinput8 doesn't work (crashes on startup). It's ermaccer's PluginMH for some reason. It plays well with ddraw, but not these two. Overload works as intended with dinput8.

**Comment by ThirteenAG** [comment] 2025-01-07 07:34
That actually reminds me that I need to fix having two asi loaders at once with an update folder.

**Comment by TemporaryPSP** [comment] 2025-01-07 08:04
Checked out PluginMH's repository and found this. I thought this was made for the latest release but it turns out it's been there for years.
> PluginMH requires https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases . Extract dinput8.dll to your Manhunt folder, then rename it to ddraw.dll.
Guess sacrifices have to be made.

**Comment by ThirteenAG** [comment] 2025-01-07 11:55
You can try the latest release, I added some code to handle the case of dll unload.

**Comment by TemporaryPSP** [comment] 2025-01-07 12:10
New version does the job just fine. Overload works with ddraw now.
